CREATE DATABASE IF NOT EXISTS viagens;

CREATE TABLE viagens.usuarios (
	id INT KEY AUTO_INCREMENT COMMENT "IDENTIFICADOR UNICO DO USUÁRIO",
    nome VARCHAR (255) NOT NULL COMMENT "NOME DO USUÁRIO",
    email VARCHAR (100) NOT NULL UNIQUE COMMENT "EMAIL EXCLUSIVO DO USUÁRIO",
    endereco VARCHAR (50) NOT NULL COMMENT "ENDEREÇO DO USUÁRIO",
    data_de_nascimento DATE NOT NULL COMMENT "DATA DE NASCIMENTO DO USUÁRIO"
);


CREATE TABLE viagens.destinos (
	id INT KEY AUTO_INCREMENT,
    nome VARCHAR (255) NOT NULL UNIQUE COMMENT "Nome do destino",
    descricao VARCHAR (255) NOT NULL COMMENT "Descrição do destino"
);

CREATE TABLE viagens.reservas (
	id INT KEY AUTO_INCREMENT COMMENT "IDENTIFICADOR UNICO DA RESERVA",
    id_usuario INT COMMENT "CHAVE ESTRANGEIRA DO USUÁRIO QUE FEZ A RESERVA", 
    --Sem Foreign Key por enquanto.
    id_destino INT COMMENT "CHAVE ESTRANGEIRA DO DESTINO DA RESERVA",
    data DATE COMMENT "DATA DA RESERVA",
    status VARCHAR (255) DEFAULT "PENDENTE" COMMENT "STATUS DA RESERVA (CONFIRMADA, PENDENTE, CANCELADA, ETC.)"
);